#include <openword/Document.h>
#include <iostream>

using namespace openword;

int main() {
    Document doc;
    
    doc.addHtml("<h1>Rich Text / HTML Engine Demo</h1>");
    doc.addHtml("<p>This document tests the <b>HTML to OOXML</b> conversion feature.</p>");
    
    doc.addHtml("<h2>1. Text Formatting</h2>");
    doc.addHtml("<p>We support <b>Bold</b>, <i>Italic</i>, <u>Underline</u>, <s>Strikethrough</s>, and nested combinations like <b><i>Bold Italic</i></b>.</p>");
    
    doc.addHtml("<h2>2. Inline Colors</h2>");
    doc.addHtml("<p>Colors can be set using standard CSS <code>color</code> tags: <span style=\"color: #FF0000\">Red</span>, <span style=\"color: #00FF00\">Green</span>, and <span style=\"color: #0000FF\">Blue</span>.</p>");
    
    doc.addHtml("<h2>3. Line Breaks and Sub/Superscript</h2>");
    doc.addHtml("<p>Water is H<sub>2</sub>O and Einstein's equation is E = mc<sup>2</sup>.<br>Here is a new line generated by an HTML <code>&lt;br&gt;</code> tag.</p>");

    doc.addHtml("<h2>4. Links</h2>");
    doc.addHtml("<p>Visit our <a href=\"https://google.com\">Website</a> for more details.</p>");

    doc.addHtml("<h2>5. Nested Structures (Tables)</h2>");
    auto table = doc.addTable(2, 2);
    table.setBorders(BorderSettings{BorderStyle::Single, 4, "000000"});
    table.cell(0, 0).addHtml("<b>Header A</b>");
    table.cell(0, 1).addHtml("<b>Header B</b>");
    table.cell(1, 0).addHtml("<span style=\"color: #888888\">Data 1</span>");
    table.cell(1, 1).addHtml("<i>Data 2</i><br>Extra Line");

    std::string outputPath = "Html_Conversion_Demo.docx";
    if (doc.save(outputPath.c_str())) {
        std::cout << "✅ Successfully generated " << outputPath << "\n";
    } else {
        std::cerr << "❌ Failed to save document.\n";
    }
    
    return 0;
}
