file(READ "${RESOURCE_IN}" content HEX)
string(REGEX MATCHALL ".." content_hex "${content}")
set(content_c "")
foreach(hex ${content_hex})
    string(APPEND content_c "0x${hex}, ")
endforeach()
file(WRITE "${HEADER_OUT}" "namespace openword_resources {\nconst unsigned char ${VARIABLE_NAME}[] = { ${content_c}0x00 };\nconst unsigned int ${VARIABLE_NAME}_LEN = sizeof(${VARIABLE_NAME}) - 1;\n}\n")
